// This file is autogenerated by VESC Tool

#ifndef ES_QMLUI_HW_H_
#define ES_QMLUI_HW_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_HW_SIZE		3686

// Variables
extern uint8_t data_qml_hw[];

// ES_QMLUI_HW_H_
#endif
