// This file is autogenerated by VESC Tool

#ifndef ES_QMLUI_APP_H_
#define ES_QMLUI_APP_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_QML_APP_SIZE		3699

// Variables
extern uint8_t data_qml_app[];

// ES_QMLUI_APP_H_
#endif
